name: Lint
on: pull_request

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['7.4']
        databases: ['sqlite']
        server-versions: ['stable20']

    name: php-cs check php${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up php
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: composer i

      - name: Run coding standards check
        run: composer run cs:check
  
  front-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
        matrix:
          node-version: ['stable']
          databases: ['sqlite']
          server-version: ['stable20']
      
    name: jscsslint check js${{ matrix.node-version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Install dependencies
        run: npm install
      
      - name: Check Lint
        run: npm run lint
